import 'package:flutter/material.dart';
import 'package:testeteladelogin/Controller/Dados.dart';
import 'package:testeteladelogin/Model/metodosTela.dart';

class TelaExercicios extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(corFundoExercicio),
      body: Container(
        padding: EdgeInsets.only(top: 20, right: 40, left: 40, bottom: 20),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            pularLinha(20),
            caixaDeTexto("Exercícios", corExercicio, 30, TextAlign.center, fonte),
            pularLinha(20),
            caixaDeTexto('O que você deseja exercitar hoje?', corExercicio, 15, TextAlign.center, fonte),
            pularLinha(20),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                botaoCorEstadoExercicio(
                  'Braço', 
                  context, 
                  'assets/imagens/teste/braço.png', 
                  'Lista Exercício Braço', 
                  'Braço Um', 
                  'Braço Dois', 
                  'Braço Três', 
                  'Braço Quatro', 
                  'Braço Cinco', 
                  'Braço Seis', 
                  'assets/imagens/exercicios/braco/braco1.gif', 
                  'assets/imagens/exercicios/braco/braco2.gif', 
                  'assets/imagens/exercicios/braco/braco3.gif',  
                  'assets/imagens/exercicios/braco/braco4.gif', 
                  'assets/imagens/exercicios/braco/braco5.gif',  
                  'assets/imagens/exercicios/braco/braco6.gif', 
                ),
                botaoCorEstadoExercicio(
                  'Costas', 
                  context, 
                  'assets/imagens/teste/costa.png', 
                  'Lista Exercício Costas', 
                  'Costas Um', 
                  'Costas Dois', 
                  'Costas Três', 
                  'Costas Quatro', 
                  'Costas Cinco', 
                  'Costas Seis', 
                  'assets/imagens/exercicios/costa/costa1.gif', 
                  'assets/imagens/exercicios/costa/costa2.gif', 
                  'assets/imagens/exercicios/costa/costa3.gif', 
                  'assets/imagens/exercicios/costa/costa4.gif', 
                  'assets/imagens/exercicios/costa/costa5.gif', 
                  'assets/imagens/exercicios/costa/costa6.gif',
                ),
              ],
            ),
            pularLinha(20),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                botaoCorEstadoExercicio(
                  'Peito', 
                  context, 
                  'assets/imagens/teste/peito.png', 
                 'Lista Exercício Peito', 
                  'Peito Um', 
                  'Peito Dois', 
                  'Peito Três', 
                  'Peito Quatro', 
                  'Peito Cinco', 
                  'Peito Seis', 
                  'assets/imagens/exercicios/peito/peito1.gif', 
                  'assets/imagens/exercicios/peito/peito2.gif', 
                  'assets/imagens/exercicios/peito/peito3.gif', 
                  'assets/imagens/exercicios/peito/peito4.gif',
                  'assets/imagens/exercicios/peito/peito5.gif', 
                  'assets/imagens/exercicios/peito/peito6.gif',
                ),
                botaoCorEstadoExercicio(
                  'Abdômen', 
                  context, 
                  'assets/imagens/teste/abdomen.png', 
                  'Lista Exercício Abdômen', 
                  'Abdômen Um', 
                  'Abdômen Dois', 
                  'Abdômen Três', 
                  'Abdômen Quatro', 
                  'Abdômen Cinco', 
                  'Abdômen Seis', 
                  'assets/imagens/exercicios/abdomen/abdomen1.gif', 
                  'assets/imagens/exercicios/abdomen/abdomen2.gif',
                  'assets/imagens/exercicios/abdomen/abdomen3.gif',  
                  'assets/imagens/exercicios/abdomen/abdomen4.gif',
                  'assets/imagens/exercicios/abdomen/abdomen5.gif',
                  'assets/imagens/exercicios/abdomen/abdomen6.gif',
                ),
              ],
            ),
            pularLinha(20),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                botaoCorEstadoExercicio(
                  'Perna', 
                  context, 
                  'assets/imagens/teste/perna.png', 
                  'Lista Exercício Perna', 
                  'Perna Um', 
                  'Perna Dois', 
                  'Perna Três', 
                  'Perna Quatro', 
                  'Perna Cinco', 
                  'Perna Seis', 
                  'assets/imagens/exercicios/peito/peito1.gif', 
                  'assets/imagens/exercicios/perna/perna2.gif', 
                  'assets/imagens/exercicios/perna/perna3.gif', 
                  'assets/imagens/exercicios/perna/perna4.gif', 
                  'assets/imagens/exercicios/perna/perna5.gif',
                  'assets/imagens/exercicios/perna/perna6.gif',
                ),
                botaoCorEstadoExercicio(
                  'Alongamento', 
                  context, 
                  'assets/imagens/teste/alongamento.png', 
                  'Lista Exercício Alongamento', 
                  'Alogamento Um', 
                  'Alogamento Dois', 
                  'Alogamento Três', 
                  'Alogamento Quatro', 
                  'Alogamento Cinco', 
                  'Alogamento Seis', 
                  'assets/imagens/exercicios/alongamento/alongamento1.gif', 
                  'assets/imagens/exercicios/alongamento/alongamento2.gif', 
                  'assets/imagens/exercicios/alongamento/alongamento3.gif', 
                  'assets/imagens/exercicios/alongamento/alongamento4.gif',  
                  'assets/imagens/exercicios/alongamento/alongamento5.gif',  
                  'assets/imagens/exercicios/alongamento/alongamento6.gif', 
                ),
              ],
            ),
            pularLinha(20),
            botaoSemBordaSair('Retornar', corExercicio, context, fonte),
          ],
        ),
      ),
    );
  }
}